dependencies:
  build: 
    - python:3.6.3
  runtime:

build_targets:

  - name: ruby27_xenial
    container:
      image: yourbase/ruby_builder_xenial:latest
    environment:
      - PREFIX=2.7
      - OS_VERSION=xenial
    commands:
      - bash ./build_all.sh

  - name: ruby26_xenial
    container:
      image: yourbase/ruby_builder_xenial:latest
    environment:
      - PREFIX=2.6
      - OS_VERSION=xenial
    commands:
      - bash ./build_all.sh

  - name: ruby25_xenial
    container:
      image: yourbase/ruby_builder_xenial:latest
    environment:
      - PREFIX=2.5
      - OS_VERSION=xenial
    commands:
      - bash ./build_all.sh

  - name: ruby24_xenial
    container:
      image: yourbase/ruby_builder_xenial:latest
    environment:
      - PREFIX=2.4
      - OS_VERSION=xenial
    commands:
      - bash ./build_all.sh


  - name: ruby23_xenial
    container:
      image: yourbase/ruby_builder_xenial:latest
    environment:
      - PREFIX=2.3
      - OS_VERSION=xenial
    commands:
      - bash ./build_all.sh

  - name: ruby22_xenial
    container:
      image: yourbase/ruby_builder_xenial:latest
    environment:
      - PREFIX=2.2
      - OS_VERSION=xenial
    commands:
      - bash ./build_all.sh

  - name: ruby21_xenial
    container:
      image: yourbase/ruby_builder_xenial:latest
    environment:
      - PREFIX=2.1
      - OS_VERSION=xenial
    commands:
      - bash ./build_all.sh


  - name: ruby27_bionic
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - PREFIX=2.7
      - OS_VERSION=bionic
    commands:
      - bash ./build_all.sh

  - name: ruby26_bionic
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - PREFIX=2.6
      - OS_VERSION=bionic
    commands:
      - bash ./build_all.sh

  - name: ruby25_bionic
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - PREFIX=2.5
      - OS_VERSION=bionic
    commands:
      - bash ./build_all.sh

  - name: ruby24_bionic
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - PREFIX=2.4
      - OS_VERSION=bionic
    commands:
      - bash ./build_all.sh


  - name: ruby23_bionic
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - PREFIX=2.3
      - OS_VERSION=bionic
      - CC=/usr/bin/gcc-6
    commands:
      - apt -y install gcc-6
      - bash ./build_all.sh

  - name: ruby22_bionic
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - PREFIX=2.2
      - OS_VERSION=bionic
      - CC=/usr/bin/gcc-6
    commands:
      - apt -y install gcc-6 
      - bash ./build_all.sh

  - name: ruby21_bionic
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - PREFIX=2.1
      - OS_VERSION=bionic
      - CC=/usr/bin/gcc-6
    commands:
      - apt -y install gcc-6
      - apt -y remove libyaml libyaml-dev
      - bash ./build_all.sh


ci:
  builds:
    - name: ruby27_xenial
      build_target: ruby27_xenial
    - name: ruby26_xenial
      build_target: ruby26_xenial
    - name: ruby25_xenial
      build_target: ruby25_xenial
    - name: ruby24_xenial
      build_target: ruby24_xenial
    - name: ruby23_xenial
      build_target: ruby23_xenial
    - name: ruby22_xenial
      build_target: ruby22_xenial
    - name: ruby21_xenial
      build_target: ruby21_xenial
    
    - name: ruby27_bionic
      build_target: ruby27_bionic
    - name: ruby26_bionic
      build_target: ruby26_bionic
    - name: ruby25_bionic
      build_target: ruby25_bionic
    - name: ruby24_bionic
      build_target: ruby24_bionic
    - name: ruby23_bionic
      build_target: ruby23_bionic
    - name: ruby22_bionic
      build_target: ruby22_bionic
    - name: ruby21_bionic
      build_target: ruby21_bionic
    









