dependencies:
  build: 
    - homebrew:latest
    - python:3.6.3
  runtime:
    - homebrew:latest

build_targets:
  - name: release
    commands:
      - pip install -r requirements.txt
      - aws s3 sync ./archives/ s3://yourbase-build-tools/ruby/ 

  - name: ruby25
    environment:
      - PREFIX=2.5
    commands:
      - brew install ruby-build
      - bash ./build_all.sh
  - name: ruby24
    environment:
      - PREFIX=2.4
    commands:
      - brew install ruby-build
      - bash ./build_all.sh
  - name: ruby23
    environment:
      - PREFIX=2.3
    commands:
      - brew install ruby-build
      - bash ./build_all.sh
  - name: ruby22
    environment:
      - PREFIX=2.2
    commands:
      - brew install ruby-build
      - bash ./build_all.sh
  - name: ruby21
    environment:
      - PREFIX=2.1
    commands:
      - brew install ruby-build
      - bash ./build_all.sh
  - name: ruby20
    environment:
      - PREFIX=2.0
    commands:
      - brew install ruby-build
      - bash ./build_all.sh

