dependencies:
  build: 
    - homebrew:latest
    - python:3.6.3
  runtime:
    - homebrew:latest

build_targets:
  - name: ubuntu1604
    container:
      image: yourbase/ruby_builder_xenial:latest
    tags:
      channel: experimental
    environment:
      - OS_VERSION=xenial
    build_after:
      - ruby27
      - ruby26
        #- ruby25
        #- ruby24
        #- ruby23
        #- ruby22
        #- ruby21
    commands:
     - pip install -r requirements.txt
     - aws s3 sync ./archives/ s3://yourbase-build-tools/ruby/ --acl public-read

  - name: ruby27
    environment:
      - PREFIX=2.7
    commands:
      - bash ./build_all.sh

  - name: ruby26
    environment:
      - PREFIX=2.6
    commands:
      - bash ./build_all.sh

  - name: ruby25
    environment:
      - PREFIX=2.5
    commands:
      - bash ./build_all.sh

  - name: ruby24
    environment:
      - PREFIX=2.4
    commands:
      - bash ./build_all.sh

  - name: ruby23
    environment:
      - PREFIX=2.3
    commands:
      - bash ./build_all.sh

  - name: ruby22
    environment:
      - PREFIX=2.2
    commands:
      - bash ./build_all.sh

  - name: ruby21
    environment:
      - PREFIX=2.1
    commands:
      - bash ./build_all.sh

  - name: ruby20
    environment:
      - PREFIX=2.0
    commands:
      - bash ./build_all.sh

ci:
  builds:
    - name: ubuntu1604
      build_target: ubuntu1604
    

